### ISSUE TITLE
Design a payment Page

### ISSUE THREAD

**Issue by treyhboy** [treyhboy/Carto#3]

**Comment by riyamendon** [comment]
How can I access your code?

**Comment by gauravsomani336** [comment]
can i start working on it @treyhboy

**Comment by treyhboy** [comment]
yes you can @gauravsomani336

**Comment by gauravsomani336** [comment]
so can you just provide me description of how it should be made and its various composition @treyhboy

**Comment by treyhboy** [comment]
@gauravsomani336 
I don't have any specific design in my mind you can refer to any shopping website payment page and make your own design accordingly

**Comment by ProgaPanda** [comment]
I see it's still not closed
