### ISSUE TITLE
Make page Responsive

### ISSUE THREAD

**Issue by treyhboy** [treyhboy/Carto#4]

**Comment by abhisartripathi** [comment]
Can I make a pull-request for this issue.

**Comment by treyhboy** [comment]
yes @abhisarautoninja

**Comment by FrancisVila** [comment]
Hi, 
@abhisarautoninja : are you working on this? I started on it before seeing that you offered to make a pull request. I don't know the etiquette / house rules too well...

**Comment by SemperDisco** [comment]
@abhisarautoninja @FrancisVila Did you resolve this issue?

**Comment by FrancisVila** [comment]
I issued a pull request: https://github.com/treyhboy/Carto/pull/20
I got a message from @treyhboy saying it was merged

**Comment by SemperDisco** [comment]
@FrancisVila I see. You can put "Closes #issue-number" in the description of the Pull Request. When you do that it links the Pull Request to the Issue and automatically closes it after the merge.

**Comment by FrancisVila** [comment]
Thanks @SemperDisco , I didn't know that!

**Comment by relense** [comment]
Is this solved?

**Comment by FrancisVila** [comment]
to me it is
